In [1]:
people = {
    'first' : ['Ram', 'Shyam', 'Binod'],
    'last' : ['Das', 'Bahadur', 'Chaudhary'],
    'email' : ['ramdas@gmail.com', 'shyambdr@gmail.com', 'binodchy@gmail.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first       last               email
0    Ram        Das    ramdas@gmail.com
1  Shyam    Bahadur  shyambdr@gmail.com
2  Binod  Chaudhary  binodchy@gmail.com

In [5]:
# Columns Value Of Data Frame:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [6]:
# Updating Columns Values As We Want:
df.columns = ['first_name', 'last_name', 'email_id']

In [7]:
df.columns

Index(['first_name', 'last_name', 'email_id'], dtype='object')

In [8]:
df

  first_name  last_name            email_id
0        Ram        Das    ramdas@gmail.com
1      Shyam    Bahadur  shyambdr@gmail.com
2      Binod  Chaudhary  binodchy@gmail.com

In [9]:
# Using List Comprehension To Upadte Columns Name:
df.columns = [x.upper() for x in df.columns]

In [10]:
df

  FIRST_NAME  LAST_NAME            EMAIL_ID
0        Ram        Das    ramdas@gmail.com
1      Shyam    Bahadur  shyambdr@gmail.com
2      Binod  Chaudhary  binodchy@gmail.com

In [11]:
# Upadting Space In Underscore:
df.columns = df.columns.str.replace('_', ' ')

In [12]:
df

  FIRST NAME  LAST NAME            EMAIL ID
0        Ram        Das    ramdas@gmail.com
1      Shyam    Bahadur  shyambdr@gmail.com
2      Binod  Chaudhary  binodchy@gmail.com

In [13]:
# Upadting Space In Underscore:
df.columns = df.columns.str.replace(' ', '_')

In [14]:
df

  FIRST_NAME  LAST_NAME            EMAIL_ID
0        Ram        Das    ramdas@gmail.com
1      Shyam    Bahadur  shyambdr@gmail.com
2      Binod  Chaudhary  binodchy@gmail.com

In [15]:
# Upadating From Upper Case To Lower Case:
df.columns = [x.lower() for x in df.columns]

In [16]:
df

  first_name  last_name            email_id
0        Ram        Das    ramdas@gmail.com
1      Shyam    Bahadur  shyambdr@gmail.com
2      Binod  Chaudhary  binodchy@gmail.com

In [17]:
# Updating Particular Columns Name Only:
df.rename(columns = {'first_name': 'first', 'last_name': 'last'}, inplace =  True)

In [18]:
df

   first       last            email_id
0    Ram        Das    ramdas@gmail.com
1  Shyam    Bahadur  shyambdr@gmail.com
2  Binod  Chaudhary  binodchy@gmail.com

In [19]:
# Updating Email Column Name Only:
df.rename(columns = {'email_id' : 'email'}, inplace = True)

In [20]:
df

   first       last               email
0    Ram        Das    ramdas@gmail.com
1  Shyam    Bahadur  shyambdr@gmail.com
2  Binod  Chaudhary  binodchy@gmail.com

In [21]:
# Upadating Only One Row Value:
df.loc[2] = ['Kamal', 'Narayan', 'kamalnry@gmail.com']

In [22]:
df

   first     last               email
0    Ram      Das    ramdas@gmail.com
1  Shyam  Bahadur  shyambdr@gmail.com
2  Kamal  Narayan  kamalnry@gmail.com

In [23]:
# Updating Particular Value In Row:
df.loc[2, ['last', 'email']] = ['Chaudhary', 'kamalchaudhary@gmail.com']

In [24]:
df

   first       last                     email
0    Ram        Das          ramdas@gmail.com
1  Shyam    Bahadur        shyambdr@gmail.com
2  Kamal  Chaudhary  kamalchaudhary@gmail.com

In [25]:
# Updating Only Last Name In 2nd Row:
df.loc[2, 'last'] = 'Narayan'

In [26]:
df

   first     last                     email
0    Ram      Das          ramdas@gmail.com
1  Shyam  Bahadur        shyambdr@gmail.com
2  Kamal  Narayan  kamalchaudhary@gmail.com

In [27]:
# Updating Values Using .at Indexer:
df.at[2, 'last'] = 'Chaudhary'

In [28]:
df

   first       last                     email
0    Ram        Das          ramdas@gmail.com
1  Shyam    Bahadur        shyambdr@gmail.com
2  Kamal  Chaudhary  kamalchaudhary@gmail.com

In [29]:
# Looking For Particular Row To Change Value Using Filter:
filt = (df['email'] == 'kamalchaudhary@gmail.com')

In [30]:
df[filt]

   first       last                     email
2  Kamal  Chaudhary  kamalchaudhary@gmail.com

In [31]:
# Looking For Last Name In Row Which We Get Using Our Filter Method:
df[filt]['last']

2    Chaudhary
Name: last, dtype: object

In [32]:
# df[filt]['last'] = 'Narayan' ----> This Will Give You An Error
# Instead Always Use .loc or .at Method To Set A New Value Or Upadate In Slected Row:
df.loc[filt, 'last'] = 'Narayan'

In [33]:
df

   first     last                     email
0    Ram      Das          ramdas@gmail.com
1  Shyam  Bahadur        shyambdr@gmail.com
2  Kamal  Narayan  kamalchaudhary@gmail.com

In [34]:
# Changing Multiple Rows At Once:
df['email'] = df['email'].str.upper()

In [35]:
df

   first     last                     email
0    Ram      Das          RAMDAS@GMAIL.COM
1  Shyam  Bahadur        SHYAMBDR@GMAIL.COM
2  Kamal  Narayan  KAMALCHAUDHARY@GMAIL.COM

In [36]:
# Chaging E-mail Value To Lower Case:
df['email'] = df['email'].str.lower()

In [37]:
df

   first     last                     email
0    Ram      Das          ramdas@gmail.com
1  Shyam  Bahadur        shyambdr@gmail.com
2  Kamal  Narayan  kamalchaudhary@gmail.com

## Four Methods To Upadte Values
### 1. apply
### 2. map
### 3. applymap
### 4. replace

In [38]:
df

   first     last                     email
0    Ram      Das          ramdas@gmail.com
1  Shyam  Bahadur        shyambdr@gmail.com
2  Kamal  Narayan  kamalchaudhary@gmail.com

In [39]:
# Using Apply To Get Len Of E-Mail:
df['email'].apply(len)

0    16
1    18
2    24
Name: email, dtype: int64

In [40]:
# Creating Function Which Return Email In Upper Case:
def upper_case_mail(email):
    return email.upper()

In [41]:
df['email'].apply(upper_case_mail)

0            RAMDAS@GMAIL.COM
1          SHYAMBDR@GMAIL.COM
2    KAMALCHAUDHARY@GMAIL.COM
Name: email, dtype: object

In [42]:
# Setting Value From Function In DataFrame:
df['email'] = df['email'].apply(upper_case_mail)

In [43]:
df

   first     last                     email
0    Ram      Das          RAMDAS@GMAIL.COM
1  Shyam  Bahadur        SHYAMBDR@GMAIL.COM
2  Kamal  Narayan  KAMALCHAUDHARY@GMAIL.COM

In [44]:
# Setting Lower Case To Email In DataFrame Using Lambda Function:
df['email'] = df['email'].apply(lambda x : x.lower())

In [45]:
df

   first     last                     email
0    Ram      Das          ramdas@gmail.com
1  Shyam  Bahadur        shyambdr@gmail.com
2  Kamal  Narayan  kamalchaudhary@gmail.com

In [46]:
# It Gives Us The Rows In That Give Data Along With Column Name:
# It Count Value Columns Wise
df.apply(len)

first    3
last     3
email    3
dtype: int64

In [47]:
# Setting Axis To Get Values:
# It Count Value Rows Wise
df.apply(len, axis = 'columns')

0    3
1    3
2    3
dtype: int64

In [48]:
# Getting Value 'How Much Entry or Data Is In Email Column in Give DataFrame':
len(df['email'])

3

In [49]:
# In Series DataFrame This Give In Columns Which Alphabetical Value Comes First:
# In Numerical Data It Gives Us Minimum Value:
df.apply(pd.Series.min)

first                       Kamal
last                      Bahadur
email    kamalchaudhary@gmail.com
dtype: object

In [50]:
# Lambda Function Use Only In Series:
df.apply(lambda x : x.min())

first                       Kamal
last                      Bahadur
email    kamalchaudhary@gmail.com
dtype: object

In [51]:
df.map(len)

   first  last  email
0      3     3     16
1      5     7     18
2      5     7     24

In [52]:
df.applymap(len)

C:\Users\User\AppData\Local\Temp\ipykernel_1104\1485728669.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(len)

   first  last  email
0      3     3     16
1      5     7     18
2      5     7     24

In [53]:
# Using map Instead Of applymap Method --> Cause ApplyMap Method Has Been Deprecated:
df.map(str.lower)

   first     last                     email
0    ram      das          ramdas@gmail.com
1  shyam  bahadur        shyambdr@gmail.com
2  kamal  narayan  kamalchaudhary@gmail.com

In [54]:
df

   first     last                     email
0    Ram      Das          ramdas@gmail.com
1  Shyam  Bahadur        shyambdr@gmail.com
2  Kamal  Narayan  kamalchaudhary@gmail.com

In [55]:
# Changing Particular Value Using Map Method:
df['first'].map({'Ram': 'Laxaman', 'Shyam': 'Naman'})

0    Laxaman
1      Naman
2        NaN
Name: first, dtype: object

In [56]:
df

   first     last                     email
0    Ram      Das          ramdas@gmail.com
1  Shyam  Bahadur        shyambdr@gmail.com
2  Kamal  Narayan  kamalchaudhary@gmail.com

In [57]:
# Changing Values Usinf Replace Method:
# But This Does Not Change Value in Our DataFrame:
df['first'].replace({'Ram': 'Laxaman', 'Shyam': 'Naman'})

0    Laxaman
1      Naman
2      Kamal
Name: first, dtype: object

In [58]:
# To Change Take Place In DataFrame We Have To Use:
df['first'] = df['first'].replace({'Ram' : 'Laxaman', 'Shyam' : 'Naman'})

In [59]:
df

     first     last                     email
0  Laxaman      Das          ramdas@gmail.com
1    Naman  Bahadur        shyambdr@gmail.com
2    Kamal  Narayan  kamalchaudhary@gmail.com

# Real Word Data:

In [60]:
df = pd.read_csv("DATAS/stack-overflow-developer-survey-2019/survey_results_public.csv")
schema_df = pd.read_csv("DATAS/stack-overflow-developer-survey-2019/survey_results_schema.csv")

In [62]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [63]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [65]:
# Using Rename To Change Columns In Data Frame:
# Always Check And Make Sure That Changing Column Name Is Geniune: Then Set inplace = True
df.rename(columns = {'ConvertedComp' : 'SalaryUSD'}, inplace = True)

In [66]:
df['SalaryUSD']

0            NaN
1            NaN
2         8820.0
3        61000.0
4            NaN
          ...
88878        NaN
88879        NaN
88880        NaN
88881        NaN
88882        NaN
Name: SalaryUSD, Length: 88883, dtype: float64

In [67]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [68]:
# Now Setting Yes Value = True And No Value = False Using Map Method:
df['Hobbyist'].map({'Yes' : True, 'No' : False})

0         True
1        False
2         True
3        False
4         True
         ...
88878     True
88879    False
88880    False
88881    False
88882     True
Name: Hobbyist, Length: 88883, dtype: bool

In [69]:
# Setting Value Premamnently In Our DataFrame:
# If There Is Many String Value NaN Value So Better Use Replace Method To Change:
df['Hobbyist'] = df['Hobbyist'].map({'Yes' : True, 'No' : False})

In [70]:
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,True,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,False,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",True,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,False,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,True,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,True,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,False,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,False,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,False,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,True,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy