In [1]:
import pandas as pd
import numpy as np

In [2]:
people = {
    'first' : ['Ram', 'Shyam', 'Binod', 'Hari', np.nan, None, 'NA'],
    'last' : ['Das', 'Bahadur', 'Chaudhary', 'Rai', np.nan, np.nan, 'Missing'],
    'email' : ['ramdas@gmail.com', 'shyambdr@gmail.com', 'binodchy@gmail.com', None, np.nan, 'anyone@gmail.com','NA'],
    'age' : ['35',  '45', '36', '43', None, None, 'Missing']
}

In [3]:
df = pd.DataFrame(people)

# Modifying Our DataFrame With The Help Of NumPy:
df.replace('NA', np.nan, inplace = True)
df.replace('Missing', np.nan, inplace = True)

In [4]:
df

   first       last               email   age
0    Ram        Das    ramdas@gmail.com    35
1  Shyam    Bahadur  shyambdr@gmail.com    45
2  Binod  Chaudhary  binodchy@gmail.com    36
3   Hari        Rai                None    43
4    NaN        NaN                 NaN  None
5   None        NaN    anyone@gmail.com  None
6    NaN        NaN                 NaN   NaN

In [5]:
# Dropping Rows Which Have Missing Value:
df.dropna()

   first       last               email age
0    Ram        Das    ramdas@gmail.com  35
1  Shyam    Bahadur  shyambdr@gmail.com  45
2  Binod  Chaudhary  binodchy@gmail.com  36

In [6]:
# How Does This DROPNA() Works:
# If Row Have Any Missing Value Than It Would Auto Drop That Row If All Columns Have Missing  Value Than It Would Not:
df.dropna(axis = 'index', how = 'any')

   first       last               email age
0    Ram        Das    ramdas@gmail.com  35
1  Shyam    Bahadur  shyambdr@gmail.com  45
2  Binod  Chaudhary  binodchy@gmail.com  36

In [7]:
# If We Change Above Code Here:
df.dropna(axis = 'index', how = 'all')
# Than It Would Drop Rows Which All Column Have Missing Value:

   first       last               email   age
0    Ram        Das    ramdas@gmail.com    35
1  Shyam    Bahadur  shyambdr@gmail.com    45
2  Binod  Chaudhary  binodchy@gmail.com    36
3   Hari        Rai                None    43
5   None        NaN    anyone@gmail.com  None

In [8]:
# If We Set INDEX = 'COLUMNS' and HOW = 'ALL' Then We Get Our Orginal DataFrame:
df.dropna(axis = 'columns', how = 'all')

   first       last               email   age
0    Ram        Das    ramdas@gmail.com    35
1  Shyam    Bahadur  shyambdr@gmail.com    45
2  Binod  Chaudhary  binodchy@gmail.com    36
3   Hari        Rai                None    43
4    NaN        NaN                 NaN  None
5   None        NaN    anyone@gmail.com  None
6    NaN        NaN                 NaN   NaN

In [9]:
# If We Set INDEX = 'COLUMNS' and HOW = 'ANY' Then We Get EMPTY DataFrame:
df.dropna(axis = 'columns', how = 'any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [10]:
# Using Subset To Get Values Only If email Column Have NaN Value:
df.dropna(axis = 'index', how = 'any', subset = ['email'])

   first       last               email   age
0    Ram        Das    ramdas@gmail.com    35
1  Shyam    Bahadur  shyambdr@gmail.com    45
2  Binod  Chaudhary  binodchy@gmail.com    36
5   None        NaN    anyone@gmail.com  None

In [11]:
# To Get Values Columns In Subset Must Have Missing Value:
df.dropna(axis = 'index', how = 'all', subset = ['last', 'email'])

   first       last               email   age
0    Ram        Das    ramdas@gmail.com    35
1  Shyam    Bahadur  shyambdr@gmail.com    45
2  Binod  Chaudhary  binodchy@gmail.com    36
3   Hari        Rai                None    43
5   None        NaN    anyone@gmail.com  None

In [12]:
# To Check How Many Values Are NaN:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [13]:
df.fillna('MISSING')

     first       last               email      age
0      Ram        Das    ramdas@gmail.com       35
1    Shyam    Bahadur  shyambdr@gmail.com       45
2    Binod  Chaudhary  binodchy@gmail.com       36
3     Hari        Rai             MISSING       43
4  MISSING    MISSING             MISSING  MISSING
5  MISSING    MISSING    anyone@gmail.com  MISSING
6  MISSING    MISSING             MISSING  MISSING

In [14]:
# To Get DataTypes Of Columns In Our DataFrame:
df.dtypes

first    object
last     object
email    object
age      object
dtype: object

In [15]:
# To Get Type Of Our np.nan
type(np.nan)

float

In [16]:
# Changing Our 'AGE' Data Types/Casting Data Types As Requirement: 
df['age'] = df['age'].astype(float)

In [17]:
df.dtypes

first     object
last      object
email     object
age      float64
dtype: object

In [18]:
df['age'].mean()

np.float64(39.75)

## REAL WORLD DATA

In [19]:
# Modfying Our DataFrame To Handle Missing And NaN Value:
na_vals = ['NA', 'Missing']
df1 = pd.read_csv("DATAS/stack-overflow-developer-survey-2019/survey_results_public.csv", na_values = na_vals)
schema_df = pd.read_csv("DATAS/stack-overflow-developer-survey-2019/survey_results_schema.csv")

In [20]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [21]:
df1.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [22]:
# Trying To Find Out Average Of YearsCode:
df1['YearsCode'].head(10)

0      4
1    NaN
2      3
3      3
4     16
5     13
6      6
7      8
8     12
9     12
Name: YearsCode, dtype: object

In [23]:
# To Get Unique Value Of Our DataFrame:
df1['YearsCode'].unique()

array(['4', nan, '3', '16', '13', '6', '8', '12', '2', '5', '17', '10',
       '14', '35', '7', 'Less than 1 year', '30', '9', '26', '40', '19',
       '15', '20', '28', '25', '1', '22', '11', '33', '50', '41', '18',
       '34', '24', '23', '42', '27', '21', '36', '32', '39', '38', '31',
       '37', 'More than 50 years', '29', '44', '45', '48', '46', '43',
       '47', '49'], dtype=object)

In [27]:
# Changing String Value In Integer:
df1['YearsCode'].replace('Less than 1 year', 0, inplace = True)

In [28]:
# Changing String Value In Integer:
df1['YearsCode'].replace('More than 50 years', 51, inplace = True)

In [29]:
# Checking Unique Value Of Our DataFrame:
df1['YearsCode'].unique()

array(['4', nan, '3', '16', '13', '6', '8', '12', '2', '5', '17', '10',
       '14', '35', '7', 0, '30', '9', '26', '40', '19', '15', '20', '28',
       '25', '1', '22', '11', '33', '50', '41', '18', '34', '24', '23',
       '42', '27', '21', '36', '32', '39', '38', '31', '37', 51, '29',
       '44', '45', '48', '46', '43', '47', '49'], dtype=object)

In [30]:
# Converting DF1 DataFrame 'YearsCode' From Object To Float:
# After Changing String Into Integre
df1['YearsCode'] = df1['YearsCode'].astype(float)

In [31]:
df1['YearsCode'].mean()

np.float64(11.662114216834588)